language: c
script: bash -ex .travis-ci.sh
sudo: false

os:
- linux
- osx

env:
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.1.1
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.0
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.1

matrix:
  exclude:
    - os: osx
      env: OCAML_VERSION=4.02.1 OPAM_VERSION=1.1.1
    - os: osx
      env: OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.1

addons:
  apt:
    packages:
    - libelf-dev
